export const DEFAULT_SECTORS = [
  "General Retail",
  "Motor Spares / Automotive",
  "Industrial Parts",
  "Hardware & Tools",
  "Construction",
  "Agriculture",
  "Food & Beverage",
  "Grocery",
  "Health / Medical",
  "Personal Care",
  "Pharmacy",
  "Clothing & Fashion",
  "Phones & Computers",
  "Education",
  "Tourism & Hospitality",
  "Leisure & Resorts",
  "Property",
  "Transport & Logistics",
  "Warehousing",
  "Engineering",
  "Plumbing",
  "Professional Services",
  "Jobbing Services",
  "Jewellery",
  "Perfumes & Cosmetics",
  "Spices",
  "Vehicle Dealer",
  "General Dealer",
  "Other",
];

export const DEFAULT_BUSINESS_TYPES = [
  "Wholesaler",
  "Retailer",
  "Manufacturer",
  "Distributor",
  "Digital Provider",
  "Medical",
  "Services",
];
